/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senactech.MCadastroPessoa.view;

import br.com.senactech.MCadastroPessoa.util.ValidaCPF;
import br.com.senactech.MCadastroPessoaJF.model.Carro;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static mcadastropessoaJF.MCadastroPessoaJF.cadCarros;
import static mcadastropessoaJF.MCadastroPessoaJF.cadPessoas;

/**
 *
 * @author João Vitor
 */
public class carroCadastro extends javax.swing.JFrame {

    /**
     * Creates new form carroCadastro
     */
    public carroCadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
        cadPessoas.mokPessoas();
        cadCarros.mokCarro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPessoa = new javax.swing.JTable();
        jbDeletar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbPesqCPF = new javax.swing.JButton();
        jlStatus = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jtfsNome = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfIdade = new javax.swing.JTextField();
        jrbAtivo = new javax.swing.JRadioButton();
        jrbInativo = new javax.swing.JRadioButton();
        jbSalvar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlNome = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlMarca = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jlAnoF = new javax.swing.JLabel();
        jlCor = new javax.swing.JLabel();
        jlCPF = new javax.swing.JLabel();
        jtfPlaca = new javax.swing.JTextField();
        jtfAnoFabricacao = new javax.swing.JTextField();
        jtfCor = new javax.swing.JTextField();
        jtfCPFProp = new javax.swing.JTextField();
        jbPesquisaPlaca = new javax.swing.JButton();
        jcMarca = new javax.swing.JComboBox<>();
        jlModelo = new javax.swing.JLabel();
        jlAnoM = new javax.swing.JLabel();
        jlPortas = new javax.swing.JLabel();
        jtfModelo = new javax.swing.JTextField();
        jtfAnoM = new javax.swing.JTextField();
        jtfPortas = new javax.swing.JTextField();
        jlProprietario = new javax.swing.JLabel();
        jbSalvarCarro = new javax.swing.JButton();
        jbLimparCarro = new javax.swing.JButton();

        jtPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                ".", ".", ".", "."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtPessoa);

        jbDeletar.setText("Deletar");
        jbDeletar.setEnabled(false);

        jbConfirmar.setText("Confirmar");
        jbConfirmar.setEnabled(false);

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);

        jbPesqCPF.setForeground(new java.awt.Color(0, 51, 204));
        jbPesqCPF.setText("Pesquisa CPF");

        jlStatus.setText("<html><b>Status:</b><font color=\"red\">*</font> ");

        jtfTelefone.setToolTipText("xx - xxxxxxxxx");

        jrbAtivo.setText("Ativo");

        jrbInativo.setText("Inativo");

        jbSalvar.setText("Salvar");

        jbLimpar.setText("Limpar");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro Carro");

        jSeparator3.setForeground(new java.awt.Color(204, 0, 51));

        jlNome.setText("<html><b>Nome:</b><font color=\"red\">*</font> ");

        jlEndereco.setText("<html><b>Endereco:</b><font color=\"red\">*</font> ");

        jlTelefone.setText("<html><b>Telefone:</b><font color=\"red\">*</font> ");

        jlIdade.setText("<html><b>Idade:</b><font color=\"red\">*</font> ");

        jbSair.setText("Sair");

        jSeparator4.setForeground(new java.awt.Color(204, 0, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Carro");

        jSeparator1.setForeground(new java.awt.Color(204, 0, 51));

        jSeparator2.setForeground(new java.awt.Color(204, 0, 51));

        jlMarca.setText("Marca:");

        jlPlaca.setText("Placa:");

        jlAnoF.setText("Ano F.:");

        jlCor.setText("Cor:");

        jlCPF.setText("CPF:");

        jtfPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPlacaFocusLost(evt);
            }
        });

        jtfCPFProp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCPFPropFocusLost(evt);
            }
        });
        jtfCPFProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCPFPropActionPerformed(evt);
            }
        });

        jbPesquisaPlaca.setText("Pesquisa Placa");

        jcMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Mercedes", "Jeep", "Fiat", "Mitsubishi", "Lincoln", "Land Rover", "Jaguard" }));

        jlModelo.setText("Modelo:");

        jlAnoM.setText("Ano M.:");

        jlPortas.setText("Portas:");

        jtfModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModeloActionPerformed(evt);
            }
        });

        jtfAnoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoMActionPerformed(evt);
            }
        });

        jlProprietario.setText("Proprietário...");

        jbSalvarCarro.setText("Salvar");
        jbSalvarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCarroActionPerformed(evt);
            }
        });

        jbLimparCarro.setText("Limpar");
        jbLimparCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlMarca)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlPlaca)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcMarca, 0, 112, Short.MAX_VALUE)
                                    .addComponent(jtfPlaca)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAnoF)
                                    .addComponent(jlCor)
                                    .addComponent(jlCPF))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfAnoFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jtfCor)
                                    .addComponent(jtfCPFProp))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPortas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jtfPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAnoM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfAnoM, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlModelo)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfModelo)
                                    .addComponent(jbPesquisaPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlProprietario)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbSalvarCarro)
                        .addGap(3, 3, 3)
                        .addComponent(jbLimparCarro)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jSeparator1)
                            .addGap(6, 6, 6)))
                    .addContainerGap()))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcMarca, jtfAnoFabricacao, jtfAnoM, jtfCPFProp, jtfCor, jtfPlaca, jtfPortas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPlaca)
                    .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisaPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMarca)
                    .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlModelo)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAnoF)
                    .addComponent(jtfAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAnoM)
                    .addComponent(jtfAnoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCor)
                    .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPortas)
                    .addComponent(jtfPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPF)
                    .addComponent(jtfCPFProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProprietario))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarCarro)
                    .addComponent(jbLimparCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcMarca, jtfAnoFabricacao, jtfAnoM, jtfCPFProp, jtfCor, jtfModelo, jtfPlaca, jtfPortas});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModeloActionPerformed

    private void jtfAnoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoMActionPerformed

    private void jtfCPFPropFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCPFPropFocusLost
        // TODO add your handling code here:
        if (!ValidaCPF.isCPF(jtfCPFProp.getText())) {
            JOptionPane.showMessageDialog(this,
                    "CPF informado esta incorreto!!!",
                    ".: Erro :.", JOptionPane.ERROR_MESSAGE);
            jtfCPF.requestFocus();
        } else if (cadPessoas.verCPF(jtfCPFProp.getText())) {
            int id = cadPessoas.pesqIdPes(jtfCPFProp.getText());
            jlProprietario.setText(cadPessoas.getNomePes(id));
        }
    }//GEN-LAST:event_jtfCPFPropFocusLost

    private void jtfCPFPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCPFPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCPFPropActionPerformed

    private void jtfPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPlacaFocusLost
        // TODO add your handling code here:
        String placa = jtfPlaca.getText();
        jtfPlaca.setText(placa.toUpperCase());
    }//GEN-LAST:event_jtfPlacaFocusLost
    
    private Boolean validaInputs() {
        Boolean verPlaca;
        String placa = jtfPlaca.getText().toUpperCase();
        verPlaca = (placa.length() == 7 && !cadCarros.verPlaca(placa));
        if (!verPlaca) {
            String msg = "Placa já cadastrada ou incorreta!";
            JOptionPane.showMessageDialog(this, msg, ".: Erro :.",
                    JOptionPane.ERROR_MESSAGE);
            jtfPlaca.requestFocus();
            return false;
        }
        Calendar cal = GregorianCalendar.getInstance();
        int anoAtual = cal.get(Calendar.YEAR);
        int anoF = Integer.parseInt(jtfAnoFabricacao.getText());
        if (anoF > anoAtual) {
            String msg = "Ano fabricação inválido, tente novamente!";
            JOptionPane.showMessageDialog(this, msg, ".: Erro :.",
                    JOptionPane.ERROR_MESSAGE);
            jtfAnoFabricacao.requestFocus();
            return false;
        }
        boolean testaAnoMod;
        int anoMod = Integer.parseInt(jtfAnoM.getText());
        testaAnoMod = cadCarros.verAnoMod(anoF, anoMod);
        if (!testaAnoMod) {
            String msg = "Ano modelo inválido, tente novamente!";
            JOptionPane.showMessageDialog(this, msg, ".: Erro :.",
                    JOptionPane.ERROR_MESSAGE);
            jtfAnoM.requestFocus();
            return false;
        }
        return true;
    }

    private void jbSalvarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCarroActionPerformed
        // TODO add your handling code here:
        if (validaInputs()) {
            int id = cadCarros.gerarId();
            int idPessoa = cadPessoas.pesqIdPes(jtfCPFProp.getText());
            String placa = jtfPlaca.getText();
            String marca = jcMarca.getSelectedItem().toString();
            String modelo = jtfModelo.getText();
            int anoF = Integer.parseInt(jtfAnoFabricacao.getText());
            int anoM = Integer.parseInt(jtfAnoM.getText());
            String cor = jtfCor.getText();
            int portas = Integer.parseInt(jtfPortas.getText());
            
            Carro c = new Carro(idPessoa, placa, marca, modelo, anoF, anoM, cor,
                    portas, idPessoa);
            cadCarros.add(c);
            
            JOptionPane.showMessageDialog(this, "Carro foi salvo com sucesso!");
            System.out.println(cadCarros.getAll());
            
        }

    }//GEN-LAST:event_jbSalvarCarroActionPerformed

    private void jbLimparCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCarroActionPerformed
        // TODO add your handling code here:
        jtfPlaca.setText("");
        jcMarca.setSelectedIndex(0);
        jtfCor.setText("");
        jtfCPF.setText("");
        jtfModelo.setText("");
        jtfAnoM.setText("");
        jtfPortas.setText("");
        jlProprietario.setText("Proprietário...");
        
    }//GEN-LAST:event_jbLimparCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carroCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carroCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimparCarro;
    private javax.swing.JButton jbPesqCPF;
    private javax.swing.JButton jbPesquisaPlaca;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvarCarro;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JLabel jlAnoF;
    private javax.swing.JLabel jlAnoM;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCor;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JLabel jlPortas;
    private javax.swing.JLabel jlProprietario;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JRadioButton jrbAtivo;
    private javax.swing.JRadioButton jrbInativo;
    private javax.swing.JTable jtPessoa;
    private javax.swing.JTextField jtfAnoFabricacao;
    private javax.swing.JTextField jtfAnoM;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfCPFProp;
    private javax.swing.JTextField jtfCor;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPlaca;
    private javax.swing.JTextField jtfPortas;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfsNome;
    // End of variables declaration//GEN-END:variables
}
